# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 22:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=4)),
                ('possible', models.DecimalField(decimal_places=2, max_digits=4)),
                ('grade_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GradeCalcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradecalc', models.CharField(choices=[('Standard', 'Standard'), ('Weight', 'Weight'), ('Declining', 'Declining'), ('DBTC', 'Dont Break the Chain'), ('Time', 'Time')], max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GradeConfigs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('percentoftotal', models.DecimalField(decimal_places=3, max_digits=8)),
                ('goal', models.CharField(max_length=255)),
                ('configtype', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade_calc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsapp.GradeCalcs')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradevalue', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F')], max_length=2)),
                ('minrange', models.IntegerField()),
                ('maxrange', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MetricConfigs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metricname', models.CharField(max_length=255)),
                ('fitbitvalue', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('metrictype', models.CharField(max_length=255)),
                ('orderby', models.IntegerField()),
                ('profiledisplay', models.BooleanField()),
                ('updateable', models.BooleanField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetricGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsapp.Grades')),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('metric_config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsapp.MetricConfigs')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('note_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='metricgrades',
            name='metric_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsapp.Metrics'),
        ),
        migrations.AddField(
            model_name='gradeconfigs',
            name='metric_config_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsapp.MetricConfigs'),
        ),
        migrations.AddField(
            model_name='dailygrades',
            name='grade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsapp.Grades'),
        ),
    ]
