# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsapp', '0004_auto_20161226_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeconfig',
            name='percentoftotal',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
