# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsapp', '0006_auto_20161226_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeconfig',
            name='configtype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gradeconfig',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradeconfig',
            name='percentoftotal',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
