# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsapp', '0008_auto_20161227_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricconfig',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
